#!/bin/bash

usage() {
	echo "Usage: $0 -b \"Background Command\" Foreground-Command [args...]"
	exit 1
}

while getopts b:h OPT
do
	case $OPT in
		b)
			BACKGROUND_COMMAND=$OPTARG
			;;
		h)
			usage
			;;
	esac
done

shift $(($OPTIND - 1))

if [ $# -eq 0 ]; then
	usage
fi
if [ -z "$BACKGROUND_COMMAND" ]; then
	usage
fi

FOREGROUND_COMMAND=$*

setsid $(cd $(dirname $0); pwd)/double-internal "$BACKGROUND_COMMAND" "$FOREGROUND_COMMAND"
