#!/bin/bash

usage() {
	echo "Usage: $0 -b \"Background Command\" Foreground-Command [args...]"
	exit 1
}

while getopts b:h OPT
do
	case $OPT in
		b)
			BACKGROUND_COMMAND=$OPTARG
			;;
		h)
			usage
			;;
	esac
done

shift $(($OPTIND - 1))

if [ $# -eq 0 ]; then
	usage
fi

FOREGROUND_COMMAND=$*

wrapper() {
	trap "exit" INT TERM
	trap "kill 0" EXIT

	$BACKGROUND_COMMAND &

	$FOREGROUND_COMMAND
}

setsid wrapper
